# Generated by Django 5.1.1 on 2024-09-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='importants',
            new_name='important',
        ),
    ]
